### ISSUE TITLE
visionOS support

### ISSUE THREAD

**Issue by RomanPodymov** [Conviva/ConvivaAVFoundation#10]
Hello.
Thank you for ConvivaAVFoundation.
Found out that you added support for visionOS in ConvivaSDK, but what about ConvivaAVFoundation? Are you going to add this feature?

**Comment by smadinen** [comment]
Hi @RomanPodymov 

WIP on this already, we will keep you posted.

Thanks

**Comment by smadinen** [comment]
@RomanPodymov 

Release is available now in Github, Please check and let us know your feedback.

Thanks

**Comment by RomanPodymov** [comment]
Hello @smadinen 
ConvivaAVFoundation v.4.0.51 solves the issue, many thanks.
