### ISSUE TITLE
IDFA in ConvivaAVFoundation

### ISSUE THREAD

**Issue by RomanPodymov** [Conviva/ConvivaAVFoundation#4]
Hello.
Thank you for ConvivaAVFoundation.
I want to submit an app to the App Store that is using ConvivaAVFoundation v.3.1.12. I need to know if my app is using IDFA. As I understood ConvivaAVFoundation < 4.0.7 is using IDFA. If so, could you please explain me why are you using it? Or which ConvivaAVFoundation 3 version does not require IDFA?

**Comment by smadinen** [comment]
Hi Roman,

From 3.x.x version series, We are using IDFA in 3.0.x series (eg:., 3.0.12 and so on) and not using IDFA in 3.1.x series (eg:., 3.1.12).

From 4.x.x version series, We are using IDFA in even version series (eg:., 4.0.4, 4.0.6 and so on) and not using IDFA in odd version series (eg:., 4.0.5 and 4.0.7 and so on).

If you are using ConvivaAVFoundation 3.1.12 in your application - we are not using IDFA in it. You should be able to submit build to Appstore with out any issues. 

Same has been mentioned in the release notes. https://github.com/Conviva/ConvivaAVFoundation/releases/tag/3.1.12

Thanks.

**Comment by RomanPodymov** [comment]
Hello @smadinen 
Thank you for the clarification.
