### ISSUE TITLE
CDN Edge IP is always empty

### ISSUE THREAD

**Issue by RomanPodymov** [Conviva/ConvivaAVFoundation#5]
Hello.
Thank you for ConvivaAVFoundation.
Just want to continue the discussion here for https://github.com/Conviva/ConvivaSDK/issues/2 as it is related to ConvivaAVFoundation. Could you please confirm that ConvivaAVFoundation 3.1.12 collects **CDN Edge IP** automatically?

**Comment by smadinen** [comment]
Hi Roman,

We don't auto collect CDN Edge IP in 3.1.12.
We started auto collecting CDN Edge IP starting from 4.0.0 version.

Thanks.

**Comment by RomanPodymov** [comment]
Hello @smadinen 
Thanks for the clarification.

**Comment by RomanPodymov** [comment]
Hello @smadinen 
I'm sorry for interrupting you, but yesterday I tried ConvivaAVFoundation v.4.0.7 and it does not collect **CDN Edge IP**. Could you please name the property that I should enable for this feature?

**Comment by smadinen** [comment]
Hi @RomanPodymov 

There is a configuration parameter which has to be enabled in the portal to enable/disable CDN server IP auto detection.

Please raise a request/get in touch with the Conviva Support team to enable CDN server IP auto-detection feature for your account.

Thanks.

**Comment by RomanPodymov** [comment]
Hello @smadinen 
Thanks for the clarification.

**Comment by smadinen** [comment]
Hi @RomanPodymov 

Please reopen it if you see any issues with this again. 
Closing it for now.

Thanks.
