### ISSUE TITLE
[CISVideoAnalyticsImpl isAirPlaying]: unrecognised selector sent to instance

### ISSUE THREAD

**Issue by RomanPodymov** [Conviva/ConvivaAVFoundation#8]
Hello.
Thank you for ConvivaAVFoundation.
Now I updated ConvivaAVFoundation from 4.0.31 to 4.0.36 and getting **[CISVideoAnalyticsImpl isAirPlaying]: unrecognised selector sent to instance** on start. I am running the app on macOS 12.6.1 with M1 (Designed for iPad mode). Xcode 13.4.1.

**Comment by smadinen** [comment]
Hi @RomanPodymov 

Are you using Cocoapods ? and what's the CoreSDK version you are using ?
Is the issue specific to macOS (or) you are seeing this when you are running on iOS devices (iPhone & iPad)

**Comment by RomanPodymov** [comment]
ConvivaSDK version is 4.0.32, if you mean this.

**Comment by RomanPodymov** [comment]
And now I reproduced this on iPhone 7 with iOS 15.7.

**Comment by RomanPodymov** [comment]
Hello @smadinen 
Am I right that you cannot reproduce it on your side?

**Comment by smadinen** [comment]
@RomanPodymov I am not able to reproduce on my side yet. I will let you know if I have any updates.
Meanwhile if you have any further information on this which you think might be helpful, please share with us.

Thanks

**Comment by RomanPodymov** [comment]
Hello @smadinen 
I don't know why, but the issue is not reproducing anymore.
